import { IUser } from '@/models/user.interface';

export const MOCK_USERS: IUser[] = [
  {
    id: '1',
    user_name: 'johnsmith123',
    first_name: 'John',
    last_name: 'Smith',
    email: 'john.smith123@gmail.com',
    password: '1Abcdefg',
    repeat_password: '1Abcdefg',
    user_type: 'Admin',
  },
  {
    id: '2',
    user_name: 'sarahmiller98',
    first_name: 'Sarah',
    last_name: 'Miller',
    email: 'sarah.miller98@gmail.com',
    password: '2Bcdefgh',
    repeat_password: '2Bcdefgh',
    user_type: 'Driver',
  },
  {
    id: '3',
    user_name: 'mikejones456',
    first_name: 'Mike',
    last_name: 'Jones',
    email: 'mike.jones456@icloud.com',
    password: '3Cdefghi',
    repeat_password: '3Cdefghi',
    user_type: 'Admin',
  },
  {
    id: '4',
    user_name: 'emilybrown7',
    first_name: 'Emily',
    last_name: 'Brown',
    email: 'emily.brown7@icloud.com',
    password: '4Defghij',
    repeat_password: '4Defghij',
    user_type: 'Driver',
  },
  {
    id: '5',
    user_name: 'davidwilson22',
    first_name: 'David',
    last_name: 'Wilson',
    email: 'david.wilson22@gmail.com',
    password: '5Efghijk',
    repeat_password: '5Efghijk',
    user_type: 'Admin',
  },
  {
    id: '6',
    user_name: 'lisajohnson89',
    first_name: 'Lisa',
    last_name: 'Johnson',
    email: 'lisa.johnson89@gmail.com',
    password: '6Fghijkl',
    repeat_password: '6Fghijkl',
    user_type: 'Driver',
  },
  {
    id: '7',
    user_name: 'ryansmith333',
    first_name: 'Ryan',
    last_name: 'Smith',
    email: 'ryan.smith333@gmail.com',
    password: '7Ghijklm',
    repeat_password: '7Ghijklm',
    user_type: 'Admin',
  },
  {
    id: '8',
    user_name: 'sophiebrown654',
    first_name: 'Sophie',
    last_name: 'Brown',
    email: 'sophie.brown654@icloud.com',
    password: '8Hijklmn',
    repeat_password: '8Hijklmn',
    user_type: 'Driver',
  },
  {
    id: '9',
    user_name: 'chriscarter777',
    first_name: 'Chris',
    last_name: 'Carter',
    email: 'chris.carter777@gmail.com',
    password: '9Ijklmno',
    repeat_password: '9Ijklmno',
    user_type: 'Admin',
  },
  {
    id: '10',
    user_name: 'jessicadavis21',
    first_name: 'Jessica',
    last_name: 'Davis',
    email: 'jessica.davis21@gmail.com',
    password: '0Jklmnop',
    repeat_password: '0Jklmnop',
    user_type: 'Driver',
  },
];
